### PR TITLE
Milestone 05 : Controllers Specs

### PR DESCRIPTION
**Pull request by FaranoshAmini**
### Project requirements
 

- [x] Added `RSpec` as a gem
- [x]  Created a `Request spec` file for all your controllers
- [x]  Make sure that for each action you check:
- [x]  If the response status was correct
- [x]  If a correct template was rendered
- [x]  If the response body includes correct placeholder text

### CODE REVIEW

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @FaranoshAmini 

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [x] You didn't document your work professionally:
   - You have some poorly documented sections in your README file Like:  Future Features, Show your Support, and Acknowledgments.
   - Kindly remove all guiding sentences from all README file sections.
   
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @FaranoshAmini,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [x] As I mentioned before, You have some poorly documented sections in your README file Like: Future Features, Show your Support, and Acknowledgments. Please add meaningful data to them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by FaranoshAmini** [comment]
@Omar-Muhamad, Thanks for your kind review and feedback.

**Review by franclobo — COMMENTED** [review]
Hi @FaranoshAmini, 

descarga

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README, please put the title "Acknowledgment" before that phrase 👇🏽 

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by TadesseDev — APPROVED** [review]
### Hi @FaranoshAmini 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy (1)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewers. ✅
 - [x]  Correct GitFlow. ✅
 - [x]  Good commit history. ✅
 - [x]  Good PR title/description. ✅
 - [x]  All linters passed ✅
## Optional suggestions

- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by FaranoshAmini** [comment]
@TadesseDev, Thanks for your kind review and feedback.

**Pull request merged**
